### ISSUE TITLE
API-용량이 큰 매개변수 전송시 400 Bad Request Error

### ISSUE THREAD

**Issue by KyungHyun-Cho** [chb1828/automatic-stock-trading-system-server#75]
주식 정보 Update를 구현하던 중 오류가 발생했습니다.
내용은 제목과 같이, 용량이 큰 매개변수 전송 시 400 BadRequest Error입니다. 
7800건? 정도의 데이터를 한번에 POST로 전송하니 오류가 나더라구요.

PostMan으로 전송 시 약 7만 Line의 데이터를 전송하며,
4만 Line 전송 시에도 400 Err,
1만 Line 전송 시 201 Created 가 수신됐습니다.

한 번에 1만 Line씩 7번을 전송할 수도 있겠지만, 1만 Line을 전송하는데 2.95s가 소요된걸 생각하면
7만 Line 전송 시 약 20초의 시간이 소모..... 끔찍..

테스트용 텍스트파일은 main에 커밋해놓겠습니다.!

**Comment by KyungHyun-Cho** [comment]
앗, 제가 branch(feature-44)를 받았었네요.
여기서 main에 push하면 무슨일이 벌어질지 잘 몰라서..?
커밋 취소하고 그냥 카톡방에 보냈습니다 ㅎㅎㅎ;;
늦은시간에 카톡 울리게해서 죄송함다!

**Comment by chb1828** [comment]
해결로 인한 closed
